name: project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.0
  
  firebase_auth: ^5.3.0
  firebase_core: ^3.5.0
  lottie: ^2.6.0
  font_awesome_flutter: ^10.7.0
  flutter_bloc: ^8.1.4
  bloc: ^8.1.3
  google_sign_in: ^6.1.6
  curved_navigation_bar: ^1.0.3
  image_picker: ^1.0.7
  google_nav_bar: ^5.0.6
  yaru_icons: ^2.4.0
  intl: ^0.19.0
  faker: ^2.1.0
  cached_network_image: ^3.3.1  



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  provider: ^6.1.2
  circle_nav_bar: ^2.0.1+1
  flutter_rating_bar: ^4.0.1
  google_maps_flutter: ^2.6.1  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
  - icons/stomach.png
  - icons/women.png
  - icons/brain.png
  - icons/pediatrics.png
  - icons/tooth.png
  - icons/medicine.png
  - icons/surgeon.png
  - icons/emergency.png
  - icons/drugs.png
  - icons/med.png
  - icons/aid.png
  - icons/medicinea.png
  - icons/baby-and-heart.png
  - icons/drug.png
  - images/doctor.jpg
  - images/doctorr.png
  - images/molarfilling.jpg
  - images/images.jpg
  - images/smile.jpg
  - images/drugstore.png
  - images/hospital.png
  - images/bmi.png
  - images/download.jpg
  - images/femaledoc.jpg
  - images/femaledoctor.jpg
  - images/profilepicone.jpg
  - images/profilepictwo.jpg
  - images/profilepicthree.jpg
  - images/profilepicfour.jpg
  - images/profilepicsix.jpg
  - images/profilepicfive.jpg
  - images/ghandor.jpg
  - images/personn.jpg
  - lottie/
