// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcJZepyFqcBCEydvxFw01AHCOQkRwRkD8',
    appId: '1:940342337375:web:b8f751de01a36b6e4f60ea',
    messagingSenderId: '940342337375',
    projectId: 'afro-asain',
    authDomain: 'afro-asain.firebaseapp.com',
    storageBucket: 'afro-asain.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCE9uWtzwv0J2XCyykTRx1CeEXQSrVaivc',
    appId: '1:940342337375:android:7c3dbd10c9358d9f4f60ea',
    messagingSenderId: '940342337375',
    projectId: 'afro-asain',
    storageBucket: 'afro-asain.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCa7xJLQ1t7GYW29DhR3TWrgvTd_pkn6vo',
    appId: '1:940342337375:ios:61bb1017d431e7224f60ea',
    messagingSenderId: '940342337375',
    projectId: 'afro-asain',
    storageBucket: 'afro-asain.appspot.com',
    iosBundleId: 'com.example.project',
  );
}
